using System.Drawing.Imaging;
using System.Text;
using System.Text.Json;

namespace WallTrek.Services.ImageGen
{
    public class GoogleImagenService : IImageGenerationService
    {
        private readonly string apiKey;
        private readonly string model;
        private readonly string imageSize;
        private readonly string aspectRatio;
        private readonly HttpClient httpClient;
        private const string BaseUrl = "https://generativelanguage.googleapis.com/v1beta";

        public GoogleImagenService(string apiKey, string model, string imageSize, string aspectRatio)
        {
            this.apiKey = apiKey ?? throw new ArgumentNullException(nameof(apiKey));
            this.model = model ?? throw new ArgumentNullException(nameof(model));
            this.imageSize = imageSize;
            this.aspectRatio = aspectRatio;
            this.httpClient = new HttpClient();
        }

        public async Task<ImageGenerationResult> GenerateImage(string prompt, CancellationToken cancellationToken = default)
        {
            // Gemini image models (e.g. gemini-3-pro-image-preview) use the generateContent endpoint;
            // Imagen models use the predict endpoint. The request and response shapes differ.
            return model.StartsWith("gemini", StringComparison.OrdinalIgnoreCase)
                ? await GenerateWithGemini(prompt, cancellationToken)
                : await GenerateWithImagen(prompt, cancellationToken);
        }

        private async Task<ImageGenerationResult> GenerateWithImagen(string prompt, CancellationToken cancellationToken)
        {
            var requestPayload = new
            {
                instances = new[]
                {
                    new { prompt = prompt }
                },
                parameters = new
                {
                    outputMimeType = "image/jpeg",
                    sampleCount = 1,
                    personGeneration = "ALLOW_ALL",
                    aspectRatio = this.aspectRatio,
                    imageSize = this.imageSize
                }
            };

            var jsonContent = JsonSerializer.Serialize(requestPayload);
            var content = new StringContent(jsonContent, Encoding.UTF8, "application/json");

            var url = $"{BaseUrl}/models/{model}:predict?key={apiKey}";
            var response = await httpClient.PostAsync(url, content, cancellationToken);

            if (!response.IsSuccessStatusCode)
            {
                var errorContent = await response.Content.ReadAsStringAsync(cancellationToken);
                throw new InvalidOperationException($"Google Imagen API request failed: {response.StatusCode} - {errorContent}");
            }

            var responseContent = await response.Content.ReadAsStringAsync(cancellationToken);
            using var jsonDoc = JsonDocument.Parse(responseContent);

            if (!jsonDoc.RootElement.TryGetProperty("predictions", out var predictions) || predictions.GetArrayLength() == 0)
            {
                throw new InvalidOperationException("No images were generated by Google Imagen");
            }

            if (!predictions[0].TryGetProperty("bytesBase64Encoded", out var base64Element))
            {
                throw new InvalidOperationException("No image data found in Google Imagen response");
            }

            var base64Data = base64Element.GetString();
            if (string.IsNullOrEmpty(base64Data))
            {
                throw new InvalidOperationException("Empty image data received from Google Imagen");
            }

            return new ImageGenerationResult
            {
                ImageData = Convert.FromBase64String(base64Data),
                Format = ImageFormat.Jpeg
            };
        }

        private async Task<ImageGenerationResult> GenerateWithGemini(string prompt, CancellationToken cancellationToken)
        {
            var requestPayload = new
            {
                contents = new[]
                {
                    new
                    {
                        parts = new[]
                        {
                            new { text = prompt }
                        }
                    }
                },
                generationConfig = new
                {
                    responseModalities = new[] { "IMAGE" },
                    imageConfig = new
                    {
                        aspectRatio = this.aspectRatio,
                        imageSize = this.imageSize
                    }
                }
            };

            var jsonContent = JsonSerializer.Serialize(requestPayload);
            var content = new StringContent(jsonContent, Encoding.UTF8, "application/json");

            var url = $"{BaseUrl}/models/{model}:generateContent?key={apiKey}";
            var response = await httpClient.PostAsync(url, content, cancellationToken);

            if (!response.IsSuccessStatusCode)
            {
                var errorContent = await response.Content.ReadAsStringAsync(cancellationToken);
                throw new InvalidOperationException($"Google Gemini image API request failed: {response.StatusCode} - {errorContent}");
            }

            var responseContent = await response.Content.ReadAsStringAsync(cancellationToken);
            using var jsonDoc = JsonDocument.Parse(responseContent);

            // Image data is returned as an inline base64 part: candidates[0].content.parts[].inlineData.data
            if (!jsonDoc.RootElement.TryGetProperty("candidates", out var candidates) || candidates.GetArrayLength() == 0)
            {
                throw new InvalidOperationException("No candidates returned by Google Gemini");
            }

            if (!candidates[0].TryGetProperty("content", out var contentElement)
                || !contentElement.TryGetProperty("parts", out var parts))
            {
                throw new InvalidOperationException("No content parts found in Google Gemini response");
            }

            foreach (var part in parts.EnumerateArray())
            {
                if (part.TryGetProperty("inlineData", out var inlineData)
                    && inlineData.TryGetProperty("data", out var dataElement))
                {
                    var base64Data = dataElement.GetString();
                    if (!string.IsNullOrEmpty(base64Data))
                    {
                        return new ImageGenerationResult
                        {
                            ImageData = Convert.FromBase64String(base64Data),
                            Format = ImageFormat.Png
                        };
                    }
                }
            }

            throw new InvalidOperationException("No image data found in Google Gemini response");
        }

        public void Dispose()
        {
            httpClient?.Dispose();
        }
    }
}
